services:
  database:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: "@Mohammad1382"
      MYSQL_DATABASE: "roshan_shop_db"
      MYSQL_PASSWORD: "@Mohammad1382"

    # command: mysql -u root -p @Mohammad1382 -e "CREATE DATABASE roshan_shop_db3"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    restart: on-failure
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: bash -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    depends_on:
      - database
      - backend
    volumes:
      - .:/app
    command: celery -A roshan_shop worker -l info

  celery_beat:
    build: .
    depends_on:
      - celery
      - backend
    command: celery -A roshan_shop beat -l info

volumes:
  db_data:
