services:
  db:
    image: mysql:8

    environment:
      MYSQL_DATABASE: "roshan_shop_db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "@Mohammad1382"
      MYSQL_ROOT_PASSWORD: "@Mohammad1382"
    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver"

volumes:
  db_data:
