# Generated by Django 5.1.3 on 2024-11-20 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoppcartmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppCartModel',
            new_name='ShopCartModel',
        ),
    ]
