# Generated by Django 5.1.3 on 2024-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_shoppcartmodel_shopcartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='visit_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
